### ISSUE TITLE
Some feature requests regarding inventory and provisioning

### ISSUE THREAD

**Issue by SeraphRoy** [aristanetworks/go-cvprac#17]
1. Import and save devices to a container, by hitting /inventory/add/addToInventory.do and /inventory/add/saveInventory.do endpoints

2. Import devices using csv file, by hitting /inventory/importInventoryData.do endpoint

3. ImageInfo struct in provisioning.go should also include a field called “sha512”. When you do a GET on /image/getImages.do, the response would actually contain a field called sha512, so simply adding a field in ImageInfo struct should be sufficient.

4. Support GetImageByName. I am surprised that we can only get image bundle by name but not the image it self. It should just be implemented by getting all the images using GetImages, and do a search in the list, as we don’t have generic GetImageByName endpoint in CVP itself.

**Comment by cheynearista** [comment]
All these have been implemented except for 2). We will be tracking 2) with issue #23
