### ISSUE TITLE
Update to use v2/validateAndCompareConfiglets.do

### ISSUE THREAD

**Issue by cheynearista** [aristanetworks/go-cvprac#63]
The endpoint `/provisioning/validateAndCompareConfiglets.do` is marked as deprecated starting 2020.2.
Replaced by /provisioning/v2/validateAndCompareConfiglets.do, available starting 2018.2.3
Planned deletion in 2020.3.0

**Comment by cheynearista** [comment]
Example of request and response:

POST  /web/provisioning/v2/validateAndCompareConfiglets.do  HTTP/1.1
```json
{
   "netElementId": "04:d0:47:66:a9:9c",
   "configIdList": [
      "configlet_122_2562893438626"
   ],
   "pageType": "validateConfig"
}
```

Resp
```json
{
   "reconciledConfig": "",
   "designedConfig": "",
   "total": "",
   "runningConfig": "! Command: show running-config\n!end\n",
   "warnings": [],
   "errors": [
      {
         "configletLineNo": 6,
         "error": "> crap% Invalid input at line 6",
         "configletId": "configlet_122_2562893438626"
      }
   ]
}
```

**Comment by sjindal-arista** [comment]
Hey @cheynearista , are there any more changes in provisioning APIs in the next and upcoming versions? Are they already addressed?
From the latest API documentation, I could see - ` /provisioning/v2/saveTopology.do` and `/provisioning/v3/getconfigfortask.do` corresponding to v2.

**Comment by cheynearista** [comment]
For provisioning the ones listed in the Release Notes are:
- `/provisioning/getconfigfortask`
- `/provisioning/v2/getconfigfortask`
- `/provisioning/runConfigSync.do`
- `/provisioning/validateAndCompareConfiglets.do`

Only one go-cvprac has implemented is `validateAndCompareConfiglets.do`.

`/inventory/deleteDevices.do` is another that is being changed which we need to address: 
- Marked as deprecated starting 2020.1
- Replaced by DELETE on `/inventory/devices` starting 2020.1.0
- Planned deletion after 2020.3.0 train.

**Comment by sjindal-arista** [comment]
Also, are we going to tag these commits with new version of `go-cvprac`?
The previous versions should still be available for clients (which are using older than 2020.1) to use with older tagged version of this repo.

**Comment by cheynearista** [comment]
Yes...we will tag these. The commit for this issue will be will be tagged with v2.6.0 probably. When we address the inventory delete, that will start v3.0 since from there forward it will support CVP releases >= 2020.x. Not sure a better way to address. Open to suggestions.

**Comment by sjindal-arista** [comment]
That sounds good. Marking the next one with next major version update brings clarity on changes.
Having said that, it would be good to have corresponding documentation. I don't see much of details on this in the primary Readme file, though that won't be the best place to document this kind of stuff. For starters, we can mention in the Readme that all the code is well commented and they can use a local `go doc` server to navigate.
