### ISSUE TITLE
Merge functionality from v2 to v3

### ISSUE THREAD

**Issue by hansbogert** [aristanetworks/go-cvprac#79]
In our project we are still using v2, because we need functionality like 

- https://github.com/aristanetworks/go-cvprac/pull/70
- https://github.com/aristanetworks/go-cvprac/pull/76
- https://github.com/aristanetworks/go-cvprac/pull/77

which is not in v3.

I think it was once proposed [1] by @cheynearista  to merge functionality from v2 to v3 -- I this still on the maintainers' radar? 

[1]: https://github.com/aristanetworks/go-cvprac/pull/70#issuecomment-727217455

**Comment by hansbogert** [comment]
As the holidays are over, a gentle nudge for @cheynearista :relaxed:

**Comment by cheynearista** [comment]
@hansbogert Apologies for lateness. Done.

**Comment by hansbogert** [comment]
1 year later, thanks! :D
